# This file was generated by GoReleaser. DO NOT EDIT.
cask "a365" do
  version "0.2.3"

  on_macos do
    on_intel do
      url "https://github.com/sozercan/a365cli/releases/download/v#{version}/a365_#{version}_darwin_amd64.tar.gz"
      sha256 "da620d36578f3d9d6e2d8bc02f01385d29c51f12bb9446877ca298e4979f2573"
    end
    on_arm do
      url "https://github.com/sozercan/a365cli/releases/download/v#{version}/a365_#{version}_darwin_arm64.tar.gz"
      sha256 "49a84a197b9d76176103e6e49bdd74c7acf47a66c6b955d494b52673ecd81f7d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sozercan/a365cli/releases/download/v#{version}/a365_#{version}_linux_amd64.tar.gz"
      sha256 "316cf347732df2f9feb6741e12ee8327d089e81ec74edc20776c5a5edde984a2"
    end
    on_arm do
      url "https://github.com/sozercan/a365cli/releases/download/v#{version}/a365_#{version}_linux_arm64.tar.gz"
      sha256 "debd072ddd07cd38980358e05f8e473597bd5080c8ce67c4facdaa4580e091dc"
    end
  end

  name "a365"
  desc "CLI for Microsoft 365 via agent365 MCP servers"
  homepage "https://github.com/sozercan/a365cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "a365"

  # No zap stanza required

end
