# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class A365 < Formula
  desc "CLI for Microsoft 365 via agent365 MCP servers"
  homepage "https://github.com/sozercan/a365cli"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sozercan/a365cli/releases/download/v0.3.1/a365_0.3.1_darwin_amd64.tar.gz"
      sha256 "265e86f3e16d75bd7ab71d8e5a6b6af22428b7b1b5e0413d54cdd806ec52c422"

      define_method(:install) do
        bin.install "a365"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sozercan/a365cli/releases/download/v0.3.1/a365_0.3.1_darwin_arm64.tar.gz"
      sha256 "a3a519c96c0d119c795352b7d309383d489b271575312c5f6d2595c89e82a99f"

      define_method(:install) do
        bin.install "a365"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sozercan/a365cli/releases/download/v0.3.1/a365_0.3.1_linux_amd64.tar.gz"
      sha256 "8d267023756e6612c85479b043e7af13f1eada880ace58ba69c15359707c563e"
      define_method(:install) do
        bin.install "a365"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sozercan/a365cli/releases/download/v0.3.1/a365_0.3.1_linux_arm64.tar.gz"
      sha256 "a8f9b82085e51b4ef3103dd60b59236a1f0628944dbf8b1303bac96927cc5891"
      define_method(:install) do
        bin.install "a365"
      end
    end
  end

  test do
    system "#{bin}/a365", "--version"
  end
end
