# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class A365 < Formula
  desc "CLI for Microsoft 365 via agent365 MCP servers"
  homepage "https://github.com/sozercan/a365cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sozercan/a365cli/releases/download/v0.1.0/a365_0.1.0_darwin_amd64.tar.gz"
      sha256 "d078eb66d1649260ec887b275882d4fc9715e46681a3d9b843a230158e60e4db"

      define_method(:install) do
        bin.install "a365"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sozercan/a365cli/releases/download/v0.1.0/a365_0.1.0_darwin_arm64.tar.gz"
      sha256 "54e23a6135413458e9f27e2832aa64729b61bc0f420e3031902ed9c982f8c6eb"

      define_method(:install) do
        bin.install "a365"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sozercan/a365cli/releases/download/v0.1.0/a365_0.1.0_linux_amd64.tar.gz"
      sha256 "e46d8a771efb9e9cec1a0b5522878c172e19b3c7e687d7f73a7c34afd591df25"
      define_method(:install) do
        bin.install "a365"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sozercan/a365cli/releases/download/v0.1.0/a365_0.1.0_linux_arm64.tar.gz"
      sha256 "10b46d37004841b47c013523b7b31dbbcb41bc1fa11feb645df43ca415632fdc"
      define_method(:install) do
        bin.install "a365"
      end
    end
  end

  test do
    system "#{bin}/a365", "--version"
  end
end
